---
# 找到配置文件中的cluster.name，打开该配置并设置集群名称
cluster.name: "docker-cluster"
node.name: elk-1
node.master: true
node.data: true

network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
transport.tcp.compress: true
# trial
xpack.license.self_generated.type: basic
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
## 配置内存使用用交换分区
#bootstrap.memory_lock: true
## 增加新的参数，这样head插件可以访问es (5.x版本，如果没有可以自己手动加)
#http.cors.enabled: true
#http.cors.allow-origin: "*"
#bootstrap.system_call_filter: false
#discovery.zen.ping.unicast.hosts: ["192.168.52.131:9300","192.168.52.132:9300", "192.168.52.133:9300"]
discovery.zen.minimum_master_nodes: 1
