version: '3.5'

services:
  elasticsearch:
    image: elasticsearch:latest
    volumes:
        - ./data/esdata: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - type: bind
    ports:
      - "5000:5000/tcp"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge