version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    volumes:
        - ./data/esdata: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:latest
    volumes:
      - type: bind
    ports:
      - "5000:5000/tcp"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  elk:
    driver: bridge