version: '3.5'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:latest
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk
#       environment:
#           ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#           ELASTIC_PASSWORD: changeme
#           discovery.type: single-node

    logstash:
        image: docker.elastic.co/logstash/logstash:latest
        volumes:
            - ./logstash/config/logstash.yml: /usr/share/logstash/config/logstash.yml
            - ./logstash/pipeline: /usr/share/logstash/pipeline
        ports:
            - "5000:5000"
            - "9600:9600"
        networks:
            - elk
        depends_on:
            - elasticsearch
#       environment:
#           LS_JAVA_OPTS: "-Xmx256m -Xms256m"

    kibana:
        image: docker.elastic.co/kibana/kibana:latest
        ports:
            - "5601:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
    elk:
        driver: bridge