version: '3.5'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:latest
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m" # 堆内存此处采用256M可以选择1G
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node

    logstash:
        image: docker.elastic.co/logstash/logstash:latest
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        ports:
            - "5000:5000"
            - "9600:9600"
        networks:
            - elk
        depends_on:
            - elasticsearch
        environment:
           LS_JAVA_OPTS: "-Xmx256m -Xms256m"

    kibana:
        image: docker.elastic.co/kibana/kibana:latest
        ports:
            - "5601:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

    filebeat:
        image: docker.elastic.co/beats/filebeat:latest
        networks:
            - elk
        hostname: filebeat
        container_name: filebeat
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml

    redis:
        image: redis:latest
        networks:
            elk:
        hostname: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
            - 16379:16379
        volumes:
            - ./redis/conf/redis.conf:/etc/redis/redis.conf

    nginx:
        image: nginx:latest
        networks:
            elk:
        hostname: nginx
        container_name: nginx
        restart: always
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./nginx/logs:/var/log/nginx
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d:/etc/nginx/conf.d

    es_plugin_hq:
        image: elastichq/elasticsearch-hq
        ports:
            - 5001:5000
        networks:
            elk:

    es_plugin_head:
        image: mobz/elasticsearch-head:7
        ports:
            - 9101:9100
        networks:
            elk:

networks:
    elk:
        driver: bridge