# https://www.elastic.co/guide/en/beats/filebeat/index.html
filebeat.inputs:
    - type: log
        enabled: true
        paths:
            - /var/log/system.log
            - /var/log/*.log
            - /logs/*.log
        include_lines: ['ERROR']
        # exclude_lines: ['^DBG']
        multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        multiline.negate: true
        multiline.match: after
        fields:
            level: debug
            review: 1
    - type: container
        enabled: true
        include_lines: ['ERROR']
        paths:
            - /usr/share/filebeat/dockerlogs/*/*.log
        close_timeout: 5m

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  #reload.period: 10s

setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  #host: "localhost:5601"

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
    enabled: true
    #protocol: "https"
    #api_key: "id:api_key"
    hosts: ["127.0.0.1:9200"]
    username: "elastic"
    password: "changeme"
# ------------------------------ Redis Output -------------------------------
output.redis:
    enabled: true
    hosts: ["redis:6379"]
    key: "filebeat"
    db: 0
    timeout: 60
# ------------------------------ Logstash Output -------------------------------
output.logstash:
    enabled: true
    hosts: ["logstash:5044"]
# ------------------------------ console Output -------------------------------
output.console:
    enabled: false
    pretty: true
# ================================= Processors =================================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

